# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'
services:
  schattenbuchhaltung-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.3
    volumes:
      - ./elastic-db/es01:/usr/share/elasticsearch/data/
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:9200:9200
      - 127.0.0.1:9300:9300
    networks:
      - elastic
    environment:
      - 'xpack.security.enabled=false'
      - 'discovery.type=single-node'
      - 'bootstrap.memory_lock=true'
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
  schattenbuchhaltung-kibana:
    image: docker.elastic.co/kibana/kibana:7.13.3
    container_name: schattenbuchhaltung-kibana
    ports:
      - 127.0.0.1:5601:5601
    networks:
      - elastic
    environment:
      ELASTICSEARCH_URL: http://schattenbuchhaltung-elasticsearch:9200
      ELASTICSEARCH_HOSTS: '["http://schattenbuchhaltung-elasticsearch:9200"]'
networks:
  elastic:
    driver: bridge
